-- ============================================================================
-- Migration: UUID(VARCHAR 36) → BIGINT IDENTITY — FeedItem / Spot / Notification
-- Date     : 2026-05-22
-- Author   : 황호찬
-- PR       : PR #75 — feat(T8): UUID → Long(IDENTITY) ID 변경
-- Target   : PostgreSQL
-- ============================================================================
--
-- ⚠️  파괴적 변경 (DESTRUCTIVE) — 기존 데이터 복구 불가
-- UUID 값을 숫자 ID로 변환하는 것은 기술적으로 불가능합니다.
-- 개발(로컬/스테이징) 환경 전용이며, 아래 절차대로 진행하십시오.
--
-- 변경 사항:
--   1) feed_items.id        : VARCHAR(36) → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   2) spots.id             : VARCHAR(36) → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   3) notifications.id     : VARCHAR(36) → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   4) 연관 FK 컬럼 (feed_item_id, spot_id) 전부 BIGINT로 타입 변환
--
-- 실행 절차 (개발 환경):
--   1. 서버 중지
--   2. psql -d backend_db -f docs/migrations/2026-05-22_t8_uuid_to_long.sql
--   3. application.yml → spring.jpa.hibernate.ddl-auto=create (또는 update)로 설정
--   4. 서버 재기동 — Hibernate가 새 스키마로 테이블 자동 재생성
--   5. 서버 재기동 후 ddl-auto를 validate 또는 none으로 원복
--
-- 롤백:
--   이 마이그레이션은 롤백이 불가능합니다. 실행 전 DB 전체 백업을 권장합니다.
--   (개발 DB는 초기화 후 재생성으로 대체 가능)
-- ============================================================================

BEGIN;

-- ──────────────────────────────────────────
-- 1. feed_items 연관 테이블 먼저 DROP
--    (feed_items.id를 FK로 참조하는 테이블)
-- ──────────────────────────────────────────
DROP TABLE IF EXISTS feed_bookmarks CASCADE;
DROP TABLE IF EXISTS feed_applications CASCADE;

-- ──────────────────────────────────────────
-- 2. feed_items DROP
-- ──────────────────────────────────────────
DROP TABLE IF EXISTS feed_items CASCADE;

-- ──────────────────────────────────────────
-- 3. spots 연관 테이블 먼저 DROP
--    (spots.id를 FK로 참조하는 테이블)
-- ──────────────────────────────────────────
DROP TABLE IF EXISTS spot_vote_options CASCADE;
DROP TABLE IF EXISTS spot_votes CASCADE;
DROP TABLE IF EXISTS spot_checklists CASCADE;
DROP TABLE IF EXISTS spot_files CASCADE;
DROP TABLE IF EXISTS spot_notes CASCADE;
DROP TABLE IF EXISTS spot_schedules CASCADE;
DROP TABLE IF EXISTS spot_participants CASCADE;

-- ──────────────────────────────────────────
-- 4. spots DROP
-- ──────────────────────────────────────────
DROP TABLE IF EXISTS spots CASCADE;

-- ──────────────────────────────────────────
-- 5. notifications DROP
-- ──────────────────────────────────────────
DROP TABLE IF EXISTS notifications CASCADE;

COMMIT;

-- ============================================================================
-- 이후 Hibernate ddl-auto=create 또는 update 로 서버 재기동하면
-- 새 엔티티 스키마(BIGINT IDENTITY)로 테이블이 자동 재생성됩니다.
-- ============================================================================

-- 검증 (재기동 후):
-- 1) PK 컬럼
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'feed_items' AND column_name = 'id';
-- → data_type: bigint 확인
--
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'spots' AND column_name = 'id';
-- → data_type: bigint 확인
--
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'notifications' AND column_name = 'id';
-- → data_type: bigint 확인
--
-- 2) FK 컬럼 (feed_item_id / spot_id 전체 일괄 확인)
-- SELECT table_name, column_name, data_type
--   FROM information_schema.columns
--   WHERE (table_name, column_name) IN (
--     ('feed_applications', 'feed_item_id'),
--     ('feed_bookmarks',    'feed_item_id'),
--     ('spot_participants', 'spot_id'),
--     ('spot_votes',        'spot_id'),
--     ('spot_notes',        'spot_id'),
--     ('spot_files',        'spot_id'),
--     ('spot_checklists',   'spot_id'),
--     ('spot_schedules',    'spot_id')
--   )
--   ORDER BY table_name, column_name;
-- → 모든 행의 data_type: bigint 확인
